# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Form\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 26))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuUser = QtWidgets.QMenu(self.menuTools)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/Images/menuIcon/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuUser.setIcon(icon)
        self.menuUser.setObjectName("menuUser")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_New_User = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menuIcon/Images/menuIcon/addUser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_New_User.setIcon(icon1)
        self.actionAdd_New_User.setObjectName("actionAdd_New_User")
        self.actionList_All_User = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menuIcon/Images/menuIcon/listUser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionList_All_User.setIcon(icon2)
        self.actionList_All_User.setObjectName("actionList_All_User")
        self.actionBlock_User = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/menuIcon/Images/menuIcon/blockUser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlock_User.setIcon(icon3)
        self.actionBlock_User.setObjectName("actionBlock_User")
        self.menuUser.addAction(self.actionAdd_New_User)
        self.menuUser.addAction(self.actionList_All_User)
        self.menuUser.addAction(self.actionBlock_User)
        self.menuTools.addAction(self.menuUser.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.actionAdd_New_User.setText(_translate("MainWindow", "Add New User"))
        self.actionList_All_User.setText(_translate("MainWindow", "List All User"))
        self.actionBlock_User.setText(_translate("MainWindow", "Block User"))

