# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login\loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 221)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.label.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.label_2.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.label_2.setObjectName("label_2")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(10, 100, 111, 71))
        self.btnLogin.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.btnLogin.setObjectName("btnLogin")
        self.ltxtUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtUserName.setGeometry(QtCore.QRect(130, 10, 301, 31))
        self.ltxtUserName.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.ltxtUserName.setObjectName("ltxtUserName")
        self.ltxtPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtPassword.setGeometry(QtCore.QRect(130, 50, 301, 31))
        self.ltxtPassword.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.ltxtPassword.setObjectName("ltxtPassword")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 100, 111, 71))
        self.pushButton_2.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(85, 0, 127);\n"
"border: 2px solid maroon")
        self.pushButton_2.setObjectName("pushButton_2")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(150, 83, 151, 91))
        self.dial.setObjectName("dial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UserName"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
