# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BlockUser_\BlockUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 310)
        MainWindow.setMinimumSize(QtCore.QSize(410, 310))
        MainWindow.setMaximumSize(QtCore.QSize(410, 310))
        MainWindow.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(142, 12, 255);\n"
"border: 2px solid #694F56")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.label_3.setObjectName("label_3")
        self.btnBlock = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlock.setGeometry(QtCore.QRect(10, 160, 111, 81))
        self.btnBlock.setObjectName("btnBlock")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(292, 160, 111, 81))
        self.btnClose.setObjectName("btnClose")
        self.cmbUser = QtWidgets.QComboBox(self.centralwidget)
        self.cmbUser.setGeometry(QtCore.QRect(160, 20, 241, 31))
        self.cmbUser.setObjectName("cmbUser")
        self.txtUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUserName.setGeometry(QtCore.QRect(160, 70, 241, 31))
        self.txtUserName.setObjectName("txtUserName")
        self.ltxtPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtPassword.setGeometry(QtCore.QRect(160, 120, 241, 31))
        self.ltxtPassword.setObjectName("ltxtPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select User"))
        self.label_2.setText(_translate("MainWindow", "User Name"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.btnBlock.setText(_translate("MainWindow", "Block"))
        self.btnClose.setText(_translate("MainWindow", "Close"))
