# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserOptions\AddUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.label.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 141, 31))
        self.label_2.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.label_3.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 141, 31))
        self.label_4.setStyleSheet("font: 75 italic 10pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.label_4.setObjectName("label_4")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(10, 230, 111, 61))
        self.btnSave.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.btnSave.setObjectName("btnSave")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(312, 230, 101, 61))
        self.btnClose.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.btnClose.setObjectName("btnClose")
        self.ltxtName = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtName.setGeometry(QtCore.QRect(160, 20, 291, 31))
        self.ltxtName.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.ltxtName.setObjectName("ltxtName")
        self.ltxtPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtPassword.setGeometry(QtCore.QRect(160, 120, 291, 31))
        self.ltxtPassword.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.ltxtPassword.setObjectName("ltxtPassword")
        self.ltxtPassword2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ltxtPassword2.setGeometry(QtCore.QRect(160, 170, 291, 31))
        self.ltxtPassword2.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.ltxtPassword2.setObjectName("ltxtPassword2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 70, 291, 31))
        self.comboBox.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(121, 3, 255);\n"
"border: 2px solid Royalblue")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnClose.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.label_2.setText(_translate("MainWindow", "User Type"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Confirm Password"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnClose.setText(_translate("MainWindow", "Close"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Super User"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Local User"))
